name = "quilt-template-cloudflare-workers"
type = "javascript"
account_id = ""
workers_dev = true

[build]
command = "yarn install && yarn build"

[build.upload]
format = "modules"
dir = "./build/server"
main = "./index.mjs"

[site]
bucket = "./build/assets"
entry-point = "."
